"""Add dislike_count to Card

Revision ID: 749e07fd333a
Revises: 5920dd0fda24
Create Date: 2025-06-26 09:47:57.410893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749e07fd333a'
down_revision = '5920dd0fda24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dislike_count', sa.Integer(), nullable=True))
    op.execute('UPDATE card SET dislike_count=0')
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.alter_column('dislike_count', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('dislike_count')

    # ### end Alembic commands ###
